# Netlify configuration file

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "https://mylace-backend-sc.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/reset-password/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/verify-email/*"
  to = "/index.html"
  status = 200
  force = true

# Define your build settings
[build]
  # The base directory for your frontend application
  base = "/"
  
  # The folder containing your build output
  publish = "build"

  # The command to build your frontend application
  command = "npm run build"

# Optional: Configure the functions directory if using serverless functions
# [functions]
#   directory = "netlify/functions"
